spring.application.name=question-service

spring.datasource.url=jdbc:postgresql://localhost:5432/questionDb
spring.datasource.username=postgres
spring.datasource.password=shafin123

spring.jpa.hibernate.ddl-auto = update