spring.application.name=quiz-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/quizDb
spring.datasource.username=postgres
spring.datasource.password=shafin123

spring.jpa.hibernate.ddl-auto = update